github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/app-monitoring-maintainers"

package:
  repositories:   ["index.docker.io/paketobuildpacks/new-relic","gcr.io/paketo-buildpacks/new-relic"]
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
  - registry: gcr.io
    username: _json_key
    password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   new-relic-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    com.newrelic.agent.java
    artifact_id: newrelic-agent
- id:   new-relic-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package: newrelic
- id:   new-relic-php
  uses: docker://ghcr.io/paketo-buildpacks/actions/new-relic-dependency:main
  with:
    type: php
