# Copyright 2018-2025 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:9.3.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@9.3.0"
    sha256 = "8310dc7f43a32bc307aeb5f38c2d4a6cebe4124ceb5f5654b13b58300fb306f1"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/9.3.0/newrelic-agent-9.3.0-sources.jar"
    source-sha256 = "b43852c2dc278be1a5ec1f8fb963a4673704fcf2aa5b185496cae87ebe67de8f"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/9.3.0/newrelic-agent-9.3.0.jar"
    version = "9.3.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:12.7.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@12.7.0?arch=amd64"
    sha256 = "f69031d3471d5e6e1f1ae8fca161819a9186a92dbfea2b0ef093e1259b770b1e"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v12.7.0.36.tar.gz"
    source-sha256 = "459357439b19cc19ec6a0120487810e968a270855ee0e68b111ed4ac45d6fc75"
    stacks = ["*"]
    uri = "https://download.newrelic.com/php_agent/archive/12.7.0.36/newrelic-php5-12.7.0.36-linux.tar.gz"
    version = "12.7.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.51.0:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.51.0?arch=amd64"
    sha256 = "48bc2fc7314d687f88aae4c80dcabbfc1e71c6c03c0d003a8c37b5f4857d8d21"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.51.0.tar.gz"
    source-sha256 = "6501eedd1ff28fb9c122e84ee1d4b745281eed279beefd929a7efc20e23dc965"
    stacks = ["*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.51.0/newrelic-dotnet-agent_10.51.0_amd64.tar.gz"
    version = "10.51.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
